### ISSUE TITLE
去掉 eslint-plugin-react 的依赖

### ISSUE THREAD

**Issue by Phinome** [ecomfe/eslint-config#1]
R;T
并不是所有的 project 都是 `React` 的吧，因此，去掉 `eslint-plugin-react` 提高通用性

**Comment by otakustay** [comment]
我考虑把react的拆出去，再看一下 https://github.com/not-an-aardvark/eslint-rule-composer 能不能做组合

**Comment by Phinome** [comment]
怎么有种感觉 eslint 被社区搞复杂了呢？2333. 或者再搞个 eslint-plugin-fesc-react ?

**Comment by otakustay** [comment]
其实如果不考虑检查的耗时的话，规则全开本身是没有问题的……

**Comment by otakustay** [comment]
我有个想法，把`react`和`import`这两个插件从`peerDependencies`中移除，但实际上生成配置的时候，会尝试查找这2个插件，如果插件存在就把相应的规则打开，不存在就不打开规则
这样子可以避免使用方有负担，代价是得自己记着去装这几个插件，如何？

**Comment by Phinome** [comment]
可行，提示使用方自行安装

**Comment by otakustay** [comment]
新电脑到手了，感觉良好，周末搞定这个

**Comment by otakustay** [comment]
`@1.1.0`
