### ISSUE TITLE
@typescript-eslint/naming-convention 相关报错

### ISSUE THREAD

**Issue by yzxinbj** [ecomfe/eslint-config#12]
请问在react + typescript 项目中，常用的ui组件会有 Header Footer 等组件的常用 大坨峰写法，有好的办法去除eslint 的报错吗。
Property name `Header` must match one of the following formats: camelCase

**Comment by otakustay** [comment]
比较奇怪为啥是Property name，能贴一下你的代码吗

**Comment by yzxinbj** [comment]
/WebstromProjects/baidu/yap_console/src/router/index.js
  1:1  warning  Definition for rule 'vue/component-tags-order' was not found         vue/component-tags-order
  1:1  error    Definition for rule 'vue/keyword-spacing' was not found              vue/keyword-spacing
  1:1  error    Definition for rule 'vue/max-len' was not found                      vue/max-len
  1:1  warning  Definition for rule 'vue/no-irregular-whitespace' was not found      vue/no-irregular-whitespace
  1:1  error    Definition for rule 'vue/no-reserved-component-names' was not found  vue/no-reserved-component-names
  1:1  error    Definition for rule 'vue/valid-v-bind-sync' was not found            vue/valid-v-bind-sync
  1:1  error    Definition for rule 'vue/valid-v-slot' was not found                 vue/valid-v-slot

**Comment by yzxinbj** [comment]
const {Header, Content, Footer, Sider} = Layout;
class App extends React.Component {
    state = {
        collapsed: false,
    };
    onCollapse = () => {
        this.setState({
            collapsed: !this.state.collapsed,
        });
    };
    render() {
        return (
            <Layout>
                <Sider
.....

**Comment by yzxinbj** [comment]
我暂时知道的解决办法 /* eslint-disable @typescript-eslint/naming-convention*/
