### ISSUE TITLE
console 允许 error 和 info 级别

### ISSUE THREAD

**Issue by cyseria** [ecomfe/eslint-config#22]
对于 strict，目前 `no-console` 的规则为  'error'，默认为 warn。

个人感觉 `console.info`, `warn`, `error` 等这种应该允许存在的，而不是一律不给书写。
因为这种很可能是 "故意在代码中留下的"，为了提供必要的 `debug` 所需信息，特别是基础库。

因此建议修改规则为:
```
'no-console': ['warn', {allow: ['warn', 'error', 'info']}]
```

**Comment by otakustay** [comment]
我认为OK，你发PR还是我们找个时间改

**Comment by otakustay** [comment]
我认为OK，你发PR还是我们找个时间改

**Comment by cyseria** [comment]
这周晚点 pr 吧

**Comment by cyseria** [comment]
> 我认为OK，你发PR还是我们找个时间改

这周晚点 pr 吧
