### ISSUE TITLE
配置中 @typescript-eslint/no-floating-promises 与 no-void 产生的冲突

### ISSUE THREAD

**Issue by jspopisno1** [ecomfe/eslint-config#25]
### 样例代码

```
async function a() {
   // ... 明确不太需要处理 floating promise 的问题
}

function b() {
    a() // <====== 此处为抱怨有 no-floating-promises 规则问题
}
```

### 已知

`a()` 返回的 promise 有较大信心不需要被进一步处理

### 提议的解决方案

- 比较靠谱的解决方案是 `a() => void a()`, 但这个跟现有的 `no-void` 规则又产生冲突了,
- 所以推荐配置 `'no-void': ['error', {'allowAsStatement': true}]` 以消除与 `'@typescript-eslint/no-floating-promises': ['error', {ignoreVoid: true}]`  的冲突

### 参考
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-floating-promises.md
(内网访问) http://minerva.dev.weiyun.baidu.com:8546/pages/minerva.html#/main?item=uzrv3o53kjlbcnyq10h0

### 原因

如果出现这个 error , 显式地 "要求你去看看到底发生了什么事情" 然后 "do the right thing"

**Comment by otakustay** [comment]
直接发PR吧
