### ISSUE TITLE
react/jsx-wrap-multilines规则需要更新

### ISSUE THREAD

**Issue by franckchen** [ecomfe/eslint-config#28]
eslint-plugin-react 7.5.0 - 2017-11-18 针对react/jsx-wrap-multilines规则有了新更新，支持了parens-new-line配置规则，且规则有了一定改变，而现在我们的规则里对此没有相应的更新.
此外我们spec中其实是推荐parens-new-line写法的，所以建议在普通检查中设置parens, 严格模式下parens-new-line
准备提交一个commit，望采纳~
下面是一个例子
```typescript
//  普通模式下good case, strict模式下bad case
const Hello = () => (<div>
    <p>World</p>
</div>);
```

**Comment by otakustay** [comment]
如果下面的代码，在普通模式下是good还是base来着：

```
const Hello = () => (
    <div />
);
```

**Comment by franckchen** [comment]
> 如果下面的代码，在普通模式下是good还是base来着：
> 
> ```
> const Hello = () => (
>     <div />
> );
> ```

这种在我本次提交修改前，修改后的普通模式和严格模式下都是good. 感觉也应该算是good

**Comment by franckchen** [comment]
```typescript
const Hello = () => (<div>
    <p>World</p>
</div>);
```
上面这段代码
修改前：普通模式 good, 严格模式good
修改后: 普通模式good, 严格模式bad
