### ISSUE TITLE
建议添加react/jsx-props-no-multi-spaces和react/jsx-props-no-multi-spaces两条规则检查

### ISSUE THREAD

**Issue by franckchen** [ecomfe/eslint-config#30]
[jsx-closing-tag-location](https://github.com/yannickcr/eslint-plugin-react/blob/fd94b95560df7ba11d1f90b42736179d7b5f509c/docs/rules/jsx-closing-tag-location.md) eslint-plugin-react 7.1.0 - 2017-06-13新增

[sx-props-no-multi-spaces](https://github.com/yannickcr/eslint-plugin-react/blob/fd94b95560df7ba11d1f90b42736179d7b5f509c/docs/rules/jsx-props-no-multi-spaces.md) eslint-plugin-react 7.9.0 - 2018-06-03 新增
这两条规则很实用，符合理念，建议引入
```javascript
'react/jsx-closing-tag-location': 'error',
'react/jsx-props-no-multi-spaces': 'error'
```
没啥问题的话，打算直接发个PR

**Comment by otakustay** [comment]
可以

**Comment by franckchen** [comment]
已提交
