### ISSUE TITLE
建议spaced-comment增加新exception #

### ISSUE THREAD

**Issue by franckchen** [ecomfe/eslint-config#31]
```typescript
class Project {
//#-region 关于"项目修改"的方法

//#-region 关"项目删除"的函数
}
```
//#-region用于标注代码分段，C#天生支持，是很好的梳理代码逻辑的注释功能。微软系代码如vscode常用这个功能。这个注释也被常见的ide所适配(如webstorm), 在查看代码structure会展示出来，令代码结构非常清晰。一旦在//和#之间增加空格，功能将失效
现在项目中个人也很喜欢用//#-region来梳理逻辑， 所以建议增加一个exception
如果觉得可以，将commit修改

**Comment by otakustay** [comment]
可以支持，希望提供PR

**Comment by franckchen** [comment]
已提交， diff了一下index.js和strict.js，感觉代码重叠有点多啊，不利于维护啦。打算找个时间整一下然后pr，感觉strict应该是普通的继承和覆盖。
