### ISSUE TITLE
no-use-before-define和@typescript-eslint/no-use-before-define规则冲突，导致通过typescript开发react直接报错

### ISSUE THREAD

**Issue by franckchen** [ecomfe/eslint-config#35]
哎，这个问题有点小严重的啊。
React + Typescript开发直接第一行就报错。。。

![infoflow 2021-01-22 17-01-23](https://user-images.githubusercontent.com/5096940/105469981-f3055580-5cd3-11eb-8852-bddcc9fdd6af.png)

很好复现，配置直接按下面的来即可
```javascript
const path = require('path');

module.exports = {
    extends: [
        '@ecomfe/eslint-config/strict',
        '@ecomfe/eslint-config/import/strict',
        '@ecomfe/eslint-config/react/strict',
        '@ecomfe/eslint-config/typescript/strict'
    ],
    ignorePatterns: [
        '**/{node_modules,lib}'
    ],
    parserOptions: {
        tsconfigRootDir: __dirname,
        project: 'tsconfig.json',
        ecmaFeatures: {
            jsx: true
        }
    },
    settings: {
        'import/resolver': {
            node: {
                extensions: ['.js', '.jsx', '.ts', '.tsx'],
                alias: {
                    '@': path.resolve(__dirname, '../src')
                }
            }
        }
    }
};
```

关于React提示'React' was used before it was defined.(no-use-before-define) 相关问题的讨论 https://github.com/typescript-eslint/typescript-eslint/issues/2502

需要在typescript配置中禁用no-use-before-define

另外感觉README里也要写一下react+ts开发的配置引入顺序， 应该是@ecomfe/eslint-config/react/strict在前， @ecomfe/eslint-config/typescript/strict在后

准备PR解决

**Comment by otakustay** [comment]
因为在百度我们推荐的一直是不写这个import，新的jsx transform也是不需要这个的，所以并不会遇到这问题

**Comment by franckchen** [comment]
> 因为在百度我们推荐的一直是不写这个import，新的jsx transform也是不需要这个的，所以并不会遇到这问题

嗯嗯，但是总感觉还是修一下的好,提个pr啦~
