### ISSUE TITLE
针对性修改一批typescript-eslint和eslint规则冲突引发的错误判断问题

### ISSUE THREAD

**Issue by franckchen** [ecomfe/eslint-config#56]
团队对于Typescript的使用较为深入，遇到一批关于typescript-eslint和eslint规则冲突问题， 已提交([commit](https://github.com/ecomfe/eslint-config/pull/47))望采纳~~ 如有问题会及时修改重新提交

以下为一些实例

- [@typescript-eslint/no-useless-constructor](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-useless-constructor.md)

    ```typescript
    // good 但是目前判断为bad
    class Person {
        constructor(public name: string) {
        }
    }
    ```
- [dot-notation](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/dot-notation.md)

  ```typescript
  // 在tsconfig中启用了noPropertyAccessFromIndexSignature(也推荐启用)配置时应该是good， 目前是bad
  // 有noPropertyAccessFromIndexSignature做检查其实已经足够了
  class X {
      [key: string]: number;
  }
  
  const x = new X();
  x['hello'] = 123;
  ```

    [Typescript noPropertyAccessFromIndexSignature规则](https://www.typescriptlang.org/tsconfig#noPropertyAccessFromIndexSignature)

- [no-redeclare](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-redeclare.md)

**Comment by otakustay** [comment]
是否一起补在你那个PR上，我周末来合并

**Comment by franckchen** [comment]
> 是否一起补在你那个PR上，我周末来合并

已完成和本issue的关连。 提及到的问题均已提交commit。部分提交因时间过久，重新整理了一下保持了提交线性结构，优化了提交信息~如果有问题我再修改一下~  😄
