### ISSUE TITLE
peerDependencies 中的 eslint-plugin-vue 版本较低，能否升级一下

### ISSUE THREAD

**Issue by YuYang019** [ecomfe/eslint-config#71]
目前设置的版本为 `"^7.20.0"`
最新的版本为 `8.5.0`

该问题会导致，项目升级到最新的 vue-cli 5.0 后，安装依赖时版本冲突，只能通过 --force 进行强制安装

**Comment by YuYang019** [comment]
@otakustay @Justineo

**Comment by Justineo** [comment]
eslint-plugin-vue@8 有规则引入了 breaking change，直接升级会破坏使用之前版本写的规则。

**Comment by YuYang019** [comment]
目前有升级的计划么~
