### ISSUE TITLE
eslint-plugin-vue 8+ vue/max-attributes-per-line 报错

### ISSUE THREAD

**Issue by xc1255178487** [ecomfe/eslint-config#75]
`Syntax Error: Error: .eslintrc.js:
        Configuration for rule "vue/max-attributes-per-line" is invalid:
        Value {"max":1,"allowFirstLine":true} should be number.
        Value {"max":1,"allowFirstLine":true} should NOT have additional properties.
        Value {"max":1,"allowFirstLine":true} should match some schema in anyOf.
    at Array.forEach (<anonymous>)`
直接安装最新的包，会报错，原因应该是下面的问题：
`vue/first-attribute-linebreak` rule has been added to enforce the location of the first attribute, so that option is no longer needed.[eslint-plugin-vue/issues/1628](https://github.com/vuejs/eslint-plugin-vue/issues/1628)

**Comment by otakustay** [comment]
@Justineo 确认一下？是不是`allowFirstLine`删掉就行地

**Comment by Justineo** [comment]
这个包目前对 `eslint-plugin-vue` 的依赖就是 `^7.20.0`。直接安装最新的包本来就不满足依赖的要求，这个报错是已知且符合预期的。

`eslint-plugin-vue@8` 对这条规则的配置方式引入了破坏性变更，除非移除这条规则，否则还得额外引入对 `eslint-plugin-vue` 版本的检测，我感觉没有太大必要。

**Comment by otakustay** [comment]
那么我们的README要修改一下，`npm install`命令要写`eslint-plugin-vue@7`
