### ISSUE TITLE
vue/component-name-in-template-casing 和vue文档中推荐的命名不一致

### ISSUE THREAD

**Issue by changyuqing** [ecomfe/eslint-config#77]
vue的文档中建议组件在模板中使用PascalCase命名，现在我看 vue/component-name-in-template-casing 是被重写为了kebab-case命名规则，后面会改动这条规则吗，还是会从一致性考虑，一直保留现在的kebab-case命名 @otakustay

**Comment by Justineo** [comment]
Vue 的 style guide 里面两种命名都可以的，你仔细读完吧。

**Comment by Justineo** [comment]
一些 Vue Style Guide 撰写过程中的讨论，仅供参考：https://github.com/vuejs/v2.vuejs.org/issues/1162
